name: dotnet format

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'
    - name: Test
      run: dotnet test --configuration Release --no-build
